"""empty message

Revision ID: 294d0bca2e0f
Revises: 704ae0cffd35
Create Date: 2023-03-06 01:46:49.904055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294d0bca2e0f'
down_revision = '704ae0cffd35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('reporter', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'reporter')
    # ### end Alembic commands ###
