"""empty message

Revision ID: 3027018ea7ba
Revises: 8c58d13bc651
Create Date: 2023-04-05 17:11:03.586610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3027018ea7ba'
down_revision = '8c58d13bc651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('transaction_payment', sa.Column('tpay_baid', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'transaction_payment', 'bookappointment', ['tpay_baid'], ['ba_id'])
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'transaction_payment', type_='foreignkey')
    # op.drop_column('transaction_payment', 'tpay_baid')
    # ### end Alembic commands ###
    pass
