"""empty message

Revision ID: 32355ec5de8d
Revises: 294d0bca2e0f
Create Date: 2023-04-01 17:13:33.707776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32355ec5de8d'
down_revision = '294d0bca2e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookappointment', sa.Column('ba_status2', sa.Enum('collected', 'not collected'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookappointment', 'ba_status2')
    # ### end Alembic commands ###
