"""empty message

Revision ID: 3aff5df2e854
Revises: 
Create Date: 2022-11-10 19:50:25.415704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aff5df2e854'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designer', sa.Column('desi_activationcode', sa.String(length=225), nullable=False))
    op.add_column('designer', sa.Column('desi_status', sa.Enum('actived', 'deactived'), server_default='deactived', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('designer', 'desi_status')
    op.drop_column('designer', 'desi_activationcode')
    # ### end Alembic commands ###
