"""empty message

Revision ID: 4ac22c802499
Revises: 3aff5df2e854
Create Date: 2022-11-10 20:02:33.909406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac22c802499'
down_revision = '3aff5df2e854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('cust_activationcode', sa.String(length=225), nullable=False))
    op.add_column('customer', sa.Column('cust_status', sa.Enum('actived', 'deactived'), server_default='deactived', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'cust_status')
    op.drop_column('customer', 'cust_activationcode')
    # ### end Alembic commands ###
