"""empty message

Revision ID: 632f6c4f7394
Revises: 
Create Date: 2022-08-07 18:16:25.188831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632f6c4f7394'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('like_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('like_postid', sa.Integer(), nullable=True),
    sa.Column('like_desiid', sa.Integer(), nullable=True),
    sa.Column('like_custid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['like_custid'], ['customer.cust_id'], ),
    sa.ForeignKeyConstraint(['like_desiid'], ['designer.desi_id'], ),
    sa.ForeignKeyConstraint(['like_postid'], ['posting.post_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
