"""empty message

Revision ID: 82123325a3ff
Revises: 4ac22c802499
Create Date: 2022-11-11 18:23:49.828023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82123325a3ff'
down_revision = '4ac22c802499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('cust_regdate', sa.DateTime(), nullable=True))
    op.add_column('customer', sa.Column('cust_activationdate', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_customer_cust_activationdate'), 'customer', ['cust_activationdate'], unique=False)
    op.create_index(op.f('ix_customer_cust_regdate'), 'customer', ['cust_regdate'], unique=False)
    op.drop_column('customer', 'cust_activationcode')
    op.add_column('designer', sa.Column('desi_regdate', sa.DateTime(), nullable=True))
    op.add_column('designer', sa.Column('desi_activationdate', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_designer_desi_activationdate'), 'designer', ['desi_activationdate'], unique=False)
    op.create_index(op.f('ix_designer_desi_regdate'), 'designer', ['desi_regdate'], unique=False)
    op.drop_column('designer', 'desi_activationcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designer', sa.Column('desi_activationcode', mysql.VARCHAR(length=225), nullable=False))
    op.drop_index(op.f('ix_designer_desi_regdate'), table_name='designer')
    op.drop_index(op.f('ix_designer_desi_activationdate'), table_name='designer')
    op.drop_column('designer', 'desi_activationdate')
    op.drop_column('designer', 'desi_regdate')
    op.add_column('customer', sa.Column('cust_activationcode', mysql.VARCHAR(length=225), nullable=False))
    op.drop_index(op.f('ix_customer_cust_regdate'), table_name='customer')
    op.drop_index(op.f('ix_customer_cust_activationdate'), table_name='customer')
    op.drop_column('customer', 'cust_activationdate')
    op.drop_column('customer', 'cust_regdate')
    # ### end Alembic commands ###
