"""empty message

Revision ID: 8c58d13bc651
Revises: d0d69092341c
Create Date: 2023-04-03 16:08:29.794720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c58d13bc651'
down_revision = 'd0d69092341c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('notification', sa.Column('notify_tpayid', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'notification', 'transaction_payment', ['notify_tpayid'], ['tpay_id'])
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'notification', type_='foreignkey')
    # op.drop_column('notification', 'notify_tpayid')
    # ### end Alembic commands ###
    pass
