"""empty message

Revision ID: 9547a66e190d
Revises: 
Create Date: 2023-10-14 17:53:18.222649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9547a66e190d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitylog', sa.Column('date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_activitylog_date'), 'activitylog', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activitylog_date'), table_name='activitylog')
    op.drop_column('activitylog', 'date')
    # ### end Alembic commands ###
