"""empty message

Revision ID: ba71b07e332c
Revises: 8c2629fa91fa
Create Date: 2023-02-07 21:41:44.875808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba71b07e332c'
down_revision = '8c2629fa91fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'new_admin_secretword')
    op.add_column('comment', sa.Column('com_suspend', sa.Enum('suspended', 'unsuspended'), server_default='unsuspended', nullable=True))
    op.add_column('comment', sa.Column('com_delete', sa.Enum('deleted', 'not deleted'), server_default='not deleted', nullable=True))
    op.alter_column('posting', 'post_suspend',
               existing_type=mysql.ENUM('suspended', 'unsuspended'),
               nullable=True,
               existing_server_default=sa.text("'unsuspended'"))
    op.alter_column('posting', 'post_delete',
               existing_type=mysql.ENUM('deleted', 'not deleted'),
               nullable=True,
               existing_server_default=sa.text("'not deleted'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posting', 'post_delete',
               existing_type=mysql.ENUM('deleted', 'not deleted'),
               nullable=False,
               existing_server_default=sa.text("'not deleted'"))
    op.alter_column('posting', 'post_suspend',
               existing_type=mysql.ENUM('suspended', 'unsuspended'),
               nullable=False,
               existing_server_default=sa.text("'unsuspended'"))
    op.drop_column('comment', 'com_delete')
    op.drop_column('comment', 'com_suspend')
    op.add_column('admin', sa.Column('new_admin_secretword', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
