"""empty message

Revision ID: c13edc35d777
Revises: 
Create Date: 2023-09-14 12:03:05.013652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13edc35d777'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookappointment', sa.Column('ba_paystatus', sa.Enum('pending', 'paid', 'failed'), server_default='pending', nullable=True))
    op.add_column('bookappointment', sa.Column('ba_reason', sa.String(length=255), nullable=True))
    op.add_column('customer', sa.Column('cust_state', sa.String(length=225), nullable=True))
    op.add_column('customer', sa.Column('cust_city', sa.String(length=225), nullable=True))
    op.add_column('customer', sa.Column('cust_countryid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customer', 'countries', ['cust_countryid'], ['country_id'])
    op.add_column('designer', sa.Column('desi_state', sa.String(length=225), nullable=True))
    op.add_column('designer', sa.Column('desi_city', sa.String(length=225), nullable=True))
    op.add_column('designer', sa.Column('desi_countryid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'designer', 'countries', ['desi_countryid'], ['country_id'])
    op.add_column('notification', sa.Column('notify_tpayid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notification', 'transaction_payment', ['notify_tpayid'], ['tpay_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'notify_tpayid')
    op.drop_constraint(None, 'designer', type_='foreignkey')
    op.drop_column('designer', 'desi_countryid')
    op.drop_column('designer', 'desi_city')
    op.drop_column('designer', 'desi_state')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'cust_countryid')
    op.drop_column('customer', 'cust_city')
    op.drop_column('customer', 'cust_state')
    op.drop_column('bookappointment', 'ba_reason')
    op.drop_column('bookappointment', 'ba_paystatus')
    # ### end Alembic commands ###
