"""empty message

Revision ID: c1e8a745d649
Revises: 8834ab4e7c1c
Create Date: 2023-09-13 00:59:15.537268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e8a745d649'
down_revision = '8834ab4e7c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookappointment', sa.Column('alling', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookappointment', 'alling')
    # ### end Alembic commands ###
