"""empty message

Revision ID: d0d69092341c
Revises: 32355ec5de8d
Create Date: 2023-04-01 17:42:26.025549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0d69092341c'
down_revision = '32355ec5de8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookappointment', sa.Column('ba_custstatus', sa.Enum('collected', 'not collected'), server_default='not collected', nullable=False))
    op.drop_column('bookappointment', 'ba_status2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookappointment', sa.Column('ba_status2', mysql.ENUM('collected', 'not collected'), nullable=False))
    op.drop_column('bookappointment', 'ba_custstatus')
    # ### end Alembic commands ###
